import { Platform } from 'react-native';
import { getBundleId } from 'react-native-device-info';

const shortCodes = {
  royoorder: '245bae',
  grub: '2f3120',
  gusto: 'd1b1a0',
  gokab: 'fb78f0', // live
  // gokab: '578b33', // staging
  suel: '638bd1',
  elixir: '574467',
  ace: '2d98b5',
  punnet: 'd2cca0',
  homeric: 'c8fbba',
  voltaic: 'd8473d',
  zest: '6865aa',
  empire: '79fbc8',
  expressdelivery: '6098e4',
  booziedoozie: '9f5473',
  zestyclickz: '3046ca',
  bakesale: '55534f',
  elcheregio: '3154ed',
  yaawi: '64a3e8',
  hosta: '757287',
  somame: '069701',
  goodwheelz: 'ceab64',
  tranznet: '02aad0',
  sambiga: '4fadae',
  agrionline: 'dd93ce',
  quickquick: '9bd088',
  caribeclean: 'a6bf72',
  stonses: '6acd69',
  agbdeliveries: 'e0d849',
  twofinder: '104a74',
  bookem: 'f87d4c',
  zip: '5ecbab',
  ridetci: '89e246',
  noki: '779cb6',
  driveree: '1ead91',
  rxnow: '58e790',
  seachangevending: 'caacbc',
  ored: 'fb0df5',
  orderchekout: 'f6cd9d',
  maxisdelivery: '1e1c90',
  donepacked: '4fc332',
  careworks: '81c669',
  thubaerides: '47f449',
  pinkjet: '7e0ff5',
  mokabfix: '88d242',
  botseats: 'fe9076',
  gumastas: '2cdae8',
  dishefs: '4c13fd',
  bilionza: '9a8793',
  doleypharmacy: 'e925ef',
  bezalio: 'c1ab2b',
  youchillax: 'a2c90d',
  instashop: 'cb6671',
  shoorafresh: 'bd4fe8',
  click2deliver: '6483c6',
  trucktirenow: '82c016',
  kel360: '9087f6',
  yeboy: 'e4ec39',
  moboserrandsservice: '3d2e75',
  cabway: 'e1331a',
  tajammul: '7c4e0b',
  carroai: '0d6852',
  ssuum: 'b3cc0b',
  blacnetwork: 'e51092',
  threadagain: 'a4543c',
  ezmobilefuel: 'a024bd',
  runaround: 'f2a962',
  swiftandvalu: 'f89822',
  trucxi: '3096b7',
  paysic: '786133',
  chipetaxi: '29790b',
  laundryorders: '995951',
  ineed: '10d0dd',
  nadelivery: '9aee12',
  marasym: 'af735a',
  silvestre: '5fa7f3',
  samakeemart: 'c473b2',
  seaeats: '27b6eb',
  enext: 'e36583',
  hokitch: 'bc54f4',
  foodnests: '82b5bc',
  sponge: 'c2c6c5',
  gomeat: '98f085',
  shopcentral: '9bdfac',
  skidoo: '4f130d',
  admCourier: '56383d',
  kurbsidekings: '67346e',
  movingwheelsdelivery: '46ee7c',
  safewalks: 'bb699c',
  dimavega: 'd25db3',
  skoop: 'ff2327',
  kudhyo: '300420',
  bharatMove: 'e2ec5e',
  sofia: 'e2ef1a',
  mml: '348045',
  bimol: '94fc5b',
  vendorspot: 'dfa952',
  sxm2go: 'b6e6e8',
  pinkydeli: '66c095',
  gasgiant: 'e6c73a',
  releezer: 'c2a130',
  vendoor: '203685',
  farmersouq: 'cc6a32',
  tmgShops: '6da47f',
  stitchesonsite: '5bdfee',
  easyu: '20b62b',
  mozmarcas: '53ea8a',
  // myfiji: 'a0c80e',
  myfiji: '245bae',
  fastmikes: 'd89823',
  citysuds: 'aaedee',
  homeTownDelivery: 'c49349',
  ritenow: '4b0d72',
  flit: '20c702',
  ihelp: '6c74a0',
  ullaz: '1b1c0d',
  privatepremiumpickups: '8d559d',
  fidesDelivery: 'd83920',
  bksTaxi: 'b66295',
  oxo: '48200b',
  sijang: '16b184',
  fairex: '1e3e30',
  everywhere: 'bc09ef',
  cannabisClubSF: '351b2b',
  halaTalabat: 'ccc32e',
  palmettoplus: '007b7b',
  allotaxi: '2142db',
  jadorDrive: 'a001aa',
  ubercann: '3a99ad',
  kongafood: 'c08eab',
  launch: '88cccf',
  kampick: 'd12c28',
  cabio: '476cf3',
  tumbak: '59944a',
  iPicknDrop: 'f9cf93',
  bluebolt: 'e5a64c',
  onthego: '5e0900',
  mylaglobal: 'a35cd8',
  ambutap: 'b436bb',
  sabroson: 'af268c',
  swiffyllc: 'da7ecb',
  meatEasy: '3e89e5',
  boltDelivery: '07a31a',
  gamaDelivery: 'b77561',
  hivefair: 'f0cede',
  localdropoff: '960a1f',
  ubi: '085703',
  scoopaTechnologies: '3c6a7e',
  knockknock: '3403fc',
  qrider: 'b715e7',
  dlvrd: '525456',
  timHomeServices: 'ab2892',
  beakme: '6dcadc',
  onscart: '10abb5',
  mandaExpress: 'b405dd',
  foodies: '939bd6',
  gO: 'a83053',
  bauBau: 'e5e48e',
  bookARyde: '3c4b81',
  petsChoice: 'c995df',
  heyBuddy: '66ca24',
  yoloSonic: 'fc53be',
  mrHealth: 'e04975',
  lopht: '16ab0d',
  yalary: '9571e0',
  seratho: '0aa2e4',
  xborne: '16c5f2',
  fawaz: '806be0',
  grn: 'd697e3',
  delivadrinks: 'e22dd6',
  myRide: 'f6fb25',
  getfix: '3065fd',
  slider: '3fea63',
  ICare: 'd3e178',
  dbairro: 'f3a0f7',
  delivery: 'd477fd',
  viversbox: 'aaa2b4',
  scootz: '760243',
  ola: 'e11f38',
  spliffnation: '1c98de',
  sourcesServices: '67f0c8',
  wer: 'fb5def',
  beachhop: '9199e7',
  qseek: 'a1ffe8',
  delvento: '6a617a',
  rideshare: 'd4997d',
  bua: '132c75',
  upstreet: '260629',
  newYorkMiniMart: '5e4b3b',
  airlinesRecruiter: 'deb34c',
  nineOneTwo: 'f92fea',
  trip: '89e246',
  aauJau: '326d8e',
  mediPick: 'b92261',
  meltivers: 'deca6f',
  ensoDigitalAgency: '419dc9',
  hiperAbasto: '50cb7f',
  redglee: '9e185e',
  dropItOffUsa: '9524c4',
  handyPickup: '530592',
  TJJHub: '41a3db',
  curblerLLC: '959ecf',
  cartnar: '7b87ed',
  uven: '9b8db5',
  pAS41: '200651',
  freshFarmz: 'eafe42',
  ryde: '309c33',
  waterTaxi: 'f0f44c',
  muvpod: '3cc883',
  smile: 'd3a41c',
  caronaTaxi: 'c12d06',
  arwin: '6a391a',
  marjMarketplace: 'aa4c64',
  eVSOnTheGo: '0fa442',
  kazakazi: 'ec3bf6',
  papiruki: '58e4d2',
  markSoublet: '2b77d8',
  amstaFood: '825037',
  toor: '0388b6',
  peerDeliveries: 'cd7768',
  swan: '0bd9cb',
  SCOOTUP: 'cf21cf',
  patrolNow: 'ad0c7d',
  butlerDelivery: '56086e',
  swatiRX: 'c7129e',
  chowHub: '57bab0',
  ginDeliver: 'ee3d33',
  orderFirst: 'd760c8',
  maiz: '3df0b6',
  dingDongEat: '2f2b60',
  medicab: 'b1f6f1',
  fazeiTeam: '0eca90',
  weTogether: '686b6c',
  jiffex: '67dcfd',
  clickService: 'cb17f2',
  amazingTaxi: '32e266',
  jazzyBug: '3441ec',
  myfarma: '612a45',
  valley: 'b1add5',
  kartAndKarry: '4eaab9',
  quickLube: '4ab432',
  keystoneDelivery: '87ad74',
  blueBundles: 'b245dd',
  busTaMove: '9d065e',
  atasktt: '9bbd4e',
  lunchboxSpecials: 'cfa64c',
  sorDelivery: '732007',
  grubHouse: 'd9c5ee',
  hitchDelivery: '3bc1d7',
  zoodMarket: 'b077a9',
  meow: '71f36c',
  dingDongDelivers: '380c49',
  torunz: 'f23b31',
  kurs: '046761',
  spa: 'ceeb2e',
  capitalDiagnostic: 'fd6dd6',
  abbeRides: '8501b6',
  nrsa: 'e9f97c',
  sadia: '312528',
  elentaMart: 'e084cc',
  exprexPro: 'cb98e8',
  fresHest: '7e43f5',
  servern: '1ba1e9',
  smokeRun: '545a71',
  myEvPlus: '1c7d9e',
  qdelo: '0fcc84',
  pawsee: 'bd2d83',
  hairRun: 'fabaaf',
  zuriRide: 'fa47e7',
  americanLuxury: '0015d5',
  smartMur: '780ecd',
  ouiSpeed: '089eee',
  getItSent: '9af7a9',
  easyDrink: '96eb54',
  iAmSelling: '7fd0dd',
  fifteenP: '016908',
  euodooTechnologies: 'c9d1ee',
  rota: 'e4b727',
  farmMeat: '371731',
  danielleBejjani: 'b47da2',
  yallaEat: '94679a',
  choizez: '05c28e',
  otto: 'd0121e',
  rescueRoadsideAssistance: '6355c5',
  tax_E: 'a7952f',
  baggageTaxi: '52bb0a',
  mersi: '1b308e',
  foodSpot: '1c67f3',
  karibaMart: 'c1ca39',
  sourceWith: '503079',
  apptFindr: 'ee3958',
  vdu: '181d99',
  laundroZone: '35a0ed',
  taxiolgy: '43d7df',
  swipe: '48c861',
  sheRyders: '058f37',
  kurrix: 'a11a9d',
  mrVeloz: '326609',
  greenCab: '20d107',
  axxi: 'bc1119',
  pets: '8e0436',
  getDress: '7d11ac',
  shelf: '245bae',
  baly: '3ae3ec',
  nuvoni: '0f3d8d',
  syloMart: 'f5358d',
  fairDeal: 'e5e082',
  hezniTaxi: 'fc1398',
  onTheWheel: '6b0c51',
  valleyMeats: '738e42',
  perucabs: '8b8156',
  hafizjwlry: '585d04',
  jana: '405d8d',
  myWayBill: '32f1ae',
  cattch: 'c399db',
  tezras: '424d92',
  eureka: '7feaa0',
  kaypee: 'ed9a42',
  hitaxi: 'fb240c',
  kwivar: '2037b0',
  parcel: '60277b',
  lex: 'a7f382',
  smokyKitchen: '8c4efa',
  flank: '3de814',
  zynoride: '958bb4',
  mealsarehere: 'c00a78',
  loamscape: 'ded864',
  delcolink: 'a2726b',
  youSmokeShops: '3f6e8e',
  doober: 'e8a1af',
  inmotion: '0e2db7',
  eatHalal: '607c84',
  jeevann: '31afbb',
  novamed: '3b5cd2',
  awamer: 'c6df5f',
  goTech: 'd87a1f',
  idrv: '07ba5d',
  qwiker: '9eeb4d',
  spryton: 'd0a063',
  nittosadai: '26662c',
  clickokart: 'f34c51',
  tiimo: 'aac5d5',
  verz: '2e1b4a',
  ragiomigo: '39c82e',
  jimsAutoRescue: '4fc57b',
  carryfood: '86d81e',
  nhazi: 'abaf70',
  petverse: '9d740f',
  clickndrop: '9536ba',
  lifehomefit: '191bdb',
  appi: 'e5e222',
  dbairro_: '2b7742',
  genee: '54f90f',
  speedyDelivery: '528728',
  holla: '4fe8db',
  stabex: '7678ee',
  uberWeeds: '3e90c0',
  cabPro: 'c672b6',
  pointoneExpediteDelivery: 'afd6cc',
  saamanshop: 'cedf8e',
  tdc: 'fd1259',
  giftyLeaf: 'c61dff',
  flyCommerce: '73cb91',
  pik: '970884',
  motina: 'a16093',
  hungry: '48b467',
  greenhippo: '2d6cda',
  mymeddy: 'dda7d5',
  uryd: 'dc8909',
  happySingh: '87b9fc',
  vital: 'db6f5a',
  parcelworks: '4b5376',
  usVetsDeliver: '4a533c',
  flybuilder: '7cd4bc',
  konectame: '1338c1',
  skyline: 'ce1ed6',
  rentzy: 'd4fc07',
  todaysDeliverys: '6d055a',
  locate: 'f9f1f8',
  georgiacollective: '1d7bf7',
  otgWeeds: '2a3af8',
  rumbella: 'fd2e2f',
  lincshare: '9b8d33',
  lvlup: 'b2eb09',
  glavour: '620b19',
  shipmoe: '153a1f',
  bigBayong: '5c8f1a',
  efectibo: 'c1412b',
  sooq: 'c7824a',
  hectoHomes: '186e1d',
  zynoBidandRide: '958bb4',
  glamguide: 'e428fc',
  // solace: '6d065d',
  solace: '2b7742',
  superpana: '9242b4',
  kero: '776666',
  godamPAY: '2ae863',
  housingSubsidies: '428883',
  bocch: '987b45',
  potolo: '12ada8',
  earnApp: '8d7b4c',
  aredoo: 'e5e45b',
  bukam: '1a3404',
  dot: '64f6a4',
  wizSonic: '5e15fd',
  udkay: 'bfe4de',
  hattaFoodHub: 'be22d8',
  ondgoo: '70ae69',
  zonesso: '4f459b',
  junkerz: '09811d',
  shopcart: 'ae366e',
  viralClean: 'e3166f',
  stargaze: 'cc100d',
  messiaa: 'c326b3',
  superApp: '041795',
  nounou: '7ab01a',
  laith: 'f235c4',
  liverpoolEats: '08e554',
  oaks: 'db5f29',
  buzy: '5e7246',
  etaim: '4b3283',
  dotTaxiApp: 'f9e0e1',
  airvoltTaxi: '41ca60',
  melakPharmacy: '4dbfe1',
  wiEnergi: '39c65c',
  nannyAfrica: 'a7dbf8',
  whatchaGotPickUp: '2c23b0',
  goKart: 'd162a7',
  hqiStore: 'f949d8',
  tkaff: 'abae0e',
  nool: '5de7c7',
  rally: 'b860de',
  shipSmart: 'bbfdee',
  weemoov: '23808d',
  weedLomo: '7e6463',
  ngoal: 'c05ddc',
  livraiZoo: '007f7a',
  boozeBrothers: '8006b6',
  magicalBookings: 'e6bd3a',
  ebay: 'e82ca7',
  readyToRent: '3c5b8c',
  theGenie: 'f7d4a1',
  sultanCenter: '478879',
  reedas: 'de142d',
  onebasket: '58bec9',
  zozozi: '980515',
  ekobridge: '04468e',
  ambosSafariExpress: 'ec16dd',
  zulbrand: '873380',
  emart: '6ca3a4',
  oyeeRides: '634188',
  royoRides: '87406e',
  tempcorner: '84a472',
  autobox: '5db7c1',
  emiRates: '9ba443',
  detailPros: '1a1d3b',
  blink: '49ceca',
  incubit: '9bc5da',
  virgingates: 'f5a75e',
  zuluCluch: '6347c6',
  ping: '17c374',
  chutneyeah: '85de17',
  ineeda: 'aaabf3',
  dropOff: '30f2f1',
};

const appIds = {
  royoorder: Platform.select({
    ios: 'com.codebrew.royoordersreactnative',
    android: 'com.codebrew.royoorder',
  }),
  dropOff: Platform.select({
    ios: 'com.dropoff.royorder',
    android: 'com.dropoff.royorder',
  }),
  runrun: Platform.select({
    ios: 'com.codebrew.runrun',
    android: 'com.codebrew.runrun',
  }),
  tranzit: Platform.select({
    ios: 'com.tranzit',
    android: 'com.app.tranzit',
  }),
  hmoobhub: Platform.select({
    ios: 'com.codebrew.hmoobhub',
    android: 'com.codebrew.hmoobhub',
  }),
  capcorp: Platform.select({
    ios: 'com.capcorpapp',
    android: 'com.capcorpapp',
  }),
  masa: Platform.select({
    ios: 'com.app.masa',
    android: 'com.app.masa',
  }),
  yogofood: Platform.select({
    ios: 'com.yogofood',
    android: 'com.yogofood',
  }),
  spidbi: Platform.select({
    ios: 'com.user.spidbi',
    android: 'com.user.spidbi',
  }),
  clicktoeat: Platform.select({
    ios: 'com.codebrew.clicktoeat',
    android: 'com.clicktoeat',
  }),
  instamobile: Platform.select({
    ios: 'com.instamobile',
    android: 'com.instamobile',
  }),
  bottomsup: Platform.select({
    ios: 'com.bottomsup',
    android: 'com.bottomsup',
  }),
  africanvillagemarket: Platform.select({
    ios: 'com.africanvillagemarket',
    android: 'com.africanvillagemarket',
  }),
  ufood: Platform.select({
    ios: 'com.ufood',
    android: 'com.order.ufood',
  }),
  martinionwheels: Platform.select({
    ios: 'com.martinionwheels',
    android: 'com.martinionwheels',
  }),
  blip: Platform.select({
    ios: 'com.blip',
    android: 'com.app.blip',
  }),
  helpnowrightnow: Platform.select({
    ios: 'com.helpnowrightnow',
    android: 'com.helpnowrightnow',
  }),
  cannabus: Platform.select({
    ios: 'com.cannabus',
    android: 'com.cannabus',
  }),
  govachow: Platform.select({
    ios: 'com.app.govachow',
    android: 'com.govachow',
  }),
  bustanfakieh: Platform.select({
    ios: 'com.codebrew.bustan',
    android: 'com.codebrew.bustan',
  }),
  shariff: Platform.select({
    ios: 'com.codebrew.shariff',
    android: 'com.shariffOrder.royoorder',
  }),
  gajamove: Platform.select({
    ios: 'com.codebrew.gajamove',
    android: 'com.codebrew.gajamove',
  }),
  getme: Platform.select({
    ios: 'com.codebrew.getme',
    android: 'com.codebrew.getme',
  }),
  orbit: Platform.select({
    ios: 'com.codebrew.orbit',
    android: 'com.codebrew.orbit',
  }),
  carlitoo: Platform.select({
    ios: 'com.codebrew.carlitoo',
    android: 'com.codebrew.carlitoo',
  }),
  specialhalal: Platform.select({
    ios: 'com.codebrew.specialhalal',
    android: 'com.codebrew.specialhalal',
  }),
  thehouse: Platform.select({
    ios: 'com.codebrew.thehouse',
    android: 'com.codebrew.thehouse',
  }),
  tasmeem: Platform.select({
    ios: 'com.codebrew.tasmeem',
    android: 'com.codebrew.tasmeem',
  }),
  snabbhem: Platform.select({
    ios: 'com.customer.snabbhem',
    android: 'com.customer.snabbhem',
  }),
  lastminutedress: Platform.select({
    ios: 'com.lastminutedress.order',
    android: 'com.lastminutedress.order',
  }),
  rerak: Platform.select({
    ios: 'com.codebrew.rerak',
    android: 'com.codebrew.rerak',
  }),
  yummiidash: Platform.select({
    ios: 'com.app.yummiidash',
    android: 'com.app.yummiidash',
  }),
  yoho: Platform.select({
    ios: 'com.codebrew.yoho',
    android: 'com.codebrew.yoho',
  }),
  glamsouq: Platform.select({
    ios: 'com.glamsouq.customer',
    android: 'com.glamsouq.customer',
  }),
  doctatransportation: Platform.select({
    ios: 'com.codebrew.doctatransportation',
    android: 'com.codebrew.doctatransportation',
  }),
  washvalley: Platform.select({
    ios: 'com.codebrew.washvalley',
    android: 'com.codebrew.washvalley',
  }),
  equamd: Platform.select({
    ios: 'com.codebrew.equamd',
    android: 'com.codebrew.equamd',
  }),
  hellodeliver: Platform.select({
    ios: 'com.codebrew.hellodeliver',
    android: 'com.codebrew.hellodeliver',
  }),
  hoganchef: Platform.select({
    ios: 'com.codebrew.hoganchef',
    android: 'com.codebrew.hoganchef',
  }),
  servze: Platform.select({
    ios: 'com.app.servze',
    android: 'com.servze',
  }),
  travo: Platform.select({
    ios: 'com.codebrew.travo',
    android: 'com.travo',
  }),
  cabdelivr: Platform.select({
    ios: 'com.app.cabdelivr',
    android: 'com.app.cabdelivr',
  }),
  drus: Platform.select({
    ios: 'com.drus.customer',
    android: 'com.app.drus',
  }),
  yahu: Platform.select({
    ios: 'com.yahu',
    android: 'com.yahu',
  }),
  zuzuclean: Platform.select({
    ios: 'com.zuzuclean',
    android: 'com.zuzuclean',
  }),
  towtrek: Platform.select({
    ios: 'com.app.towtrek',
    android: 'com.app.towtrek',
  }),
  arenagrub: Platform.select({
    ios: 'com.arenagrub',
    android: 'com.arenagrub',
  }),
  jet: Platform.select({
    ios: 'com.jet.customer',
    android: 'com.jet',
  }),
  africanize: Platform.select({
    ios: 'com.africanize.customer',
    android: 'com.africanize',
  }),
  markita: Platform.select({
    ios: 'com.markita',
    android: 'com.markita',
  }),
  sirvu: Platform.select({
    ios: 'com.sirvu',
    android: 'com.sirvu',
  }),
  ublue: Platform.select({
    ios: 'com.ublue',
    android: 'com.ublue',
  }),
  mstechy: Platform.select({
    ios: 'com.mstechy',
    android: 'com.mstechy',
  }),
  senshive: Platform.select({
    ios: 'com.senshive',
    android: 'com.senshive',
  }),
  ridemate: Platform.select({
    ios: 'com.ridemate',
    android: 'com.ridemate',
  }),
  codiner: Platform.select({
    ios: 'com.app.codiner',
    android: 'com.app.codiner',
  }),
  housekeeper: Platform.select({
    ios: 'com.housekeeper4hire',
    android: 'com.housekeeper',
  }),
  hairstonexpress: Platform.select({
    ios: 'com.hairstonexpress',
    android: 'com.hairstonexpress',
  }),
  diamonddashers: Platform.select({
    ios: 'com.diamonddashers',
    android: 'com.diamonddashers',
  }),
  destinationOps: Platform.select({
    ios: 'com.destinationOps',
    android: 'com.destinationOps',
  }),
  loopwhole: Platform.select({
    ios: 'com.app.loopwhole',
    android: 'com.loopwhole',
  }),
  vici: Platform.select({
    ios: 'com.customer.vici',
    android: 'com.app.vici',
  }),
  carhop: Platform.select({
    ios: 'com.carhop',
    android: 'com.carhop',
  }),
  yogolift: Platform.select({
    ios: 'com.yogolift.orders',
    android: 'com.yogolift.order',
  }),
  fleety: Platform.select({
    ios: 'com.fleety',
    android: 'com.feelty.userApp',
  }),
  flyinghorse: Platform.select({
    ios: 'com.flyinghorse',
    android: 'com.flyinghorse',
  }),
  errand: Platform.select({
    ios: 'com.errand',
    android: 'com.errand',
  }),
  partnerproject: Platform.select({
    ios: 'com.partnerproject',
    android: 'com.partnerproject',
  }),
  menus: Platform.select({
    ios: 'com.menus.customer',
    android: 'com.menus.customer',
  }),
  doorstep: Platform.select({
    ios: 'com.doorstepone',
    android: 'com.doorstep',
  }),
  sunshinerideshare: Platform.select({
    ios: 'com.app.sunshinerideshare',
    android: 'com.sunshinerideshare',
  }),
  autotek: Platform.select({
    ios: 'com.autotek',
    android: 'com.autotek',
  }),
  wegotit: Platform.select({
    ios: 'com.wegotit',
    android: 'com.wegotit',
  }),
  survuhs: Platform.select({
    ios: 'com.survuhs',
    android: 'com.survuhs',
  }),
  igolux: Platform.select({
    ios: 'com.igolux',
    android: 'com.igolux',
  }),
  toda: Platform.select({
    ios: 'com.toda.orders',
    android: 'com.toda.orders',
  }),
  mobi: Platform.select({
    ios: 'com.mobi.customer',
    android: 'com.mobi.orders',
  }),
  yourlaundryapp: Platform.select({
    ios: 'com.yourlaundryapp',
    android: 'com.yourlaundryapp',
  }),
  hemptyfy: Platform.select({
    ios: 'com.hemptyfy.orders',
    android: 'com.hemptyfy.orders',
  }),
  sharu: Platform.select({
    ios: 'com.sharu',
    android: 'com.sharu',
  }),
  smcompany: Platform.select({
    ios: 'com.smcompany',
    android: 'com.smcompany',
  }),
  totum4U: Platform.select({
    ios: 'com.totum4U',
    android: 'com.totum4U',
  }),
  hmc: Platform.select({
    ios: 'com.eatkareem.hmchalal',
    android: 'com.eatkareem.hmchalal',
  }),
  groupy: Platform.select({
    ios: 'com.app.groupy',
    android: 'com.groupy',
  }),
  weeat: Platform.select({
    ios: 'com.weeat.customer',
    android: 'com.weeat.customer',
  }),
  gorillas: Platform.select({
    ios: 'com.gorillas',
    android: 'com.gorillas',
  }),
  baytukom: Platform.select({
    ios: 'com.baytukom',
    android: 'com.baytukom',
  }),
  eboyo: Platform.select({
    ios: 'com.eboyo',
    android: 'com.eboyo',
  }),
  vecto: Platform.select({
    ios: 'com.vecto',
    android: 'com.vecto',
  }),
  share: Platform.select({
    ios: 'com.share.customer',
    android: 'com.share',
  }),
  pickmeup: Platform.select({
    ios: 'com.application.pickmeup',
    android: 'com.application.pickmeup',
  }),
  taquick: Platform.select({
    ios: 'com.taquick',
    android: 'com.taquick',
  }),
  goody: Platform.select({
    ios: 'com.goody.customer',
    android: 'com.goody',
  }),
  grub: Platform.select({
    ios: 'com.customer.grub',
    android: 'com.customer.grub',
  }),
  gusto: Platform.select({
    ios: 'com.gusto',
    android: 'com.customer.gusto',
  }),
  punnet: Platform.select({
    ios: 'com.punnet',
    android: 'com.punnet',
  }),
  homeric: Platform.select({
    ios: 'com.homeric',
    android: 'com.homeric',
  }),
  voltaic: Platform.select({
    ios: 'com.voltaic',
    android: 'com.voltaic',
  }),
  zest: Platform.select({
    ios: 'com.zest.customer',
    android: 'com.zest.customer',
  }),
  suel: Platform.select({
    ios: 'com.suel',
    android: 'com.suel',
  }),
  gokab: Platform.select({
    ios: 'com.gokab',
    android: 'com.gokab',
  }),
  elixir: Platform.select({
    ios: 'com.elixir',
    android: 'com.elixir.customer',
  }),
  ace: Platform.select({
    ios: 'com.customer.ace',
    android: 'com.customer.ace',
  }),
  skyline: Platform.select({
    ios: 'com.skyline.royoorders',
    android: 'com.skyline',
  }),
  rentzy: Platform.select({
    ios: 'com.rentzy.royoorders',
    android: 'com.rentzy',
  }),
  todaysDeliverys: Platform.select({
    ios: 'com.todaysDeliverys.royoorders',
    android: 'com.todaysDeliverys.royoorders',
  }),
  locate: Platform.select({
    ios: 'com.locate.royoorders',
    android: 'com.locate.royoorders',
  }),
  georgiacollective: Platform.select({
    ios: 'com.georgiacollective.royoorders',
    android: 'com.georgiacollective.royoorders',
  }),
  otgWeeds: Platform.select({
    ios: 'com.otgweeds.royoorders',
    android: 'com.otgweeds.royoorders',
  }),
  rumbella: Platform.select({
    ios: 'com.rumbella.royoorders',
    android: 'com.rumbella.royoorders',
  }),
  lincshare: Platform.select({
    ios: 'com.lincshare.royoorders',
    android: 'com.lincshare.royoorders',
  }),
  lvlup: Platform.select({
    ios: 'com.lvlup.royoorders',
    android: 'com.lvlup.royoorders',
  }),
  glavour: Platform.select({
    ios: 'com.glavour.royoorders',
    android: 'com.glavour.royoorders',
  }),
  shipmoe: Platform.select({
    ios: 'com.shipmoe.royoorders',
    android: 'com.shipmoe.royoorders',
  }),
  bigBayong: Platform.select({
    ios: 'com.bigBayong.royoorders',
    android: 'com.bigBayong.royoorders',
  }),
  efectibo: Platform.select({
    ios: 'com.efectibo.royoorders',
    android: 'com.efectibo.royoorders',
  }),
  sooq: Platform.select({
    ios: 'com.sooq.royoorders',
    android: 'com.sooq.royoorders',
  }),
  hectoHomes: Platform.select({
    ios: 'com.hectohomes.royoorders',
    android: 'com.hectohomes.royoorders',
  }),
  zynoBidandRide: Platform.select({
    ios: 'com.zynoapp.royoorders',
    android: 'com.zynoapp.royoorders',
  }),
  glamguide: Platform.select({
    ios: 'com.glamguide.royoorders',
    android: 'com.glamguide.royoorders',
  }),
  solace: Platform.select({
    ios: 'com.solace.royoorders',
    android: 'com.solace.royoorders',
  }),
  superpana: Platform.select({
    ios: 'com.superpana.royoorders',
    android: 'com.superpana.royoorders',
  }),
  kero: Platform.select({
    ios: 'com.kero.royoorders',
    android: 'com.kero.royoorders',
  }),
  godamPAY: Platform.select({
    ios: 'com.godamPAY.royoorders',
    android: 'com.godamPAY.royoorders',
  }),
  housingSubsidies: Platform.select({
    ios: 'com.housingSubsidies.royoorders',
    android: 'com.housingSubsidies.royoorders',
  }),
  bocch: Platform.select({
    ios: 'com.bocch.royoorders',
    android: 'com.bocch.royoorders',
  }),
  potolo: Platform.select({
    ios: 'com.potolo.royoorders',
    android: 'com.potolo.royoorders',
  }),
  earnApp: Platform.select({
    ios: 'com.earnapp.royoorders',
    android: 'com.earnapp.royoorders',
  }),
  aredoo: Platform.select({
    ios: 'com.aredoo.royoorders',
    android: 'com.aredoo.royoorders',
  }),
  bukam: Platform.select({
    ios: 'com.bukam.royoorders',
    android: 'com.bukam.order',
  }),
  dot: Platform.select({
    ios: 'com.dot.royoorders',
    android: 'com.dot.royoorders',
  }),
  wizSonic: Platform.select({
    ios: 'com.wizSonic.royoorders',
    android: 'com.wizSonic.royoorders',
  }),
  udkay: Platform.select({
    ios: 'com.udkay.royoorders',
    android: 'com.udkeyorder',
  }),
  hattaFoodHub: Platform.select({
    ios: 'com.hattafoodhub.orderapp',
    android: 'com.hattaFoodHub.order',
  }),
  ondgoo: Platform.select({
    ios: 'com.ondgoo.royoorders',
    android: 'com.ondgoo.royoorders',
  }),

  zonesso: Platform.select({
    ios: 'com.zonesso.royoorders',
    android: 'com.zonesso.royoorders',
  }),
  junkerz: Platform.select({
    ios: 'com.junkerz.royoOrders',
    android: 'com.junkerz.royoOrders',
  }),
  shopcart: Platform.select({
    ios: 'com.shopcart.royoorder',
    android: 'com.shopcart.royoorder',
  }),
  viralClean: Platform.select({
    ios: 'com.viralclean.royoorder',
    android: 'com.viralclean.royoorder',
  }),
  stargaze: Platform.select({
    ios: 'com.stargaze.royoorder',
    android: 'com.stargaze.royoorder',
  }),
  messiaa: Platform.select({
    ios: 'com.messiaa.orders',
    android: 'com.messiaa.orders',
  }),
  superApp: Platform.select({
    ios: 'com.superapp.royoorder',
    android: 'com.superapp.royoorder',
  }),
  nounou: Platform.select({
    ios: 'com.nounou.royoorder',
    android: 'com.nounou.royoorder',
  }),
  laith: Platform.select({
    ios: 'com.laith.royoorder',
    android: 'com.laith.royoorder',
  }),
  liverpoolEats: Platform.select({
    ios: 'com.liverpoolEats.royoorder',
    android: 'com.liverpoolEats.royoorder',
  }),
  oaks: Platform.select({
    ios: 'com.oaks.royoorder',
    android: 'com.oaks.royoorder',
  }),
  buzy: Platform.select({
    ios: 'com.buszy.royoorder',
    android: 'com.buszy.royoorder',
  }),
  etaim: Platform.select({
    ios: 'com.etaim.royoorder',
    android: 'com.etiam.orderApp',
  }),
  dotTaxiApp: Platform.select({
    ios: 'com.dotTaxi.order',
    android: 'com.dotTaxi.order',
  }),
  airvoltTaxi: Platform.select({
    ios: 'com.airvoltTaxi.royoorder',
    android: 'com.airvoltTaxi.royoorder',
  }),
  melakPharmacy: Platform.select({
    ios: 'com.melakPharmacy.royoorder',
    android: 'com.melakPharmacy.royoorder',
  }),
  wiEnergi: Platform.select({
    ios: 'com.wienergi.royoorder',
    android: 'com.wienergi.royoorder',
  }),
  nannyAfrica: Platform.select({
    ios: 'com.nannyafrica',
    android: 'com.nannyafrica',
  }),
  whatchaGotPickUp: Platform.select({
    ios: 'com.whatchaGotPickUp',
    android: 'com.whatchaGotPickUp',
  }),
  gokart: Platform.select({
    ios: 'com.gokart.order',
    android: 'com.gokart.order',
  }),
  hqiStore: Platform.select({
    ios: 'com.hqiStore.order',
    android: 'com.hqiStore.order',
  }),
  tkaff: Platform.select({
    ios: 'com.tkaff.order',
    android: 'com.tkaff.order',
  }),
  nool: Platform.select({
    ios: 'com.nool.order',
    android: 'com.nool.order',
  }),
  rally: Platform.select({
    ios: 'com.rally.order',
    android: 'com.rally.order',
  }),
  shipSmart: Platform.select({
    ios: 'com.shipSmart.order',
    android: 'com.shipSmart.order',
  }),
  weemoov: Platform.select({
    ios: 'com.weemoov.order',
    android: 'com.weemoov.order',
  }),
  weedLomo: Platform.select({
    ios: 'com.weedLomo.order',
    android: 'com.weedLomo.order',
  }),
  ngoal: Platform.select({
    ios: 'com.nGoal.orderApp',
    android: 'com.nGoal.order',
  }),
  livraiZoo: Platform.select({
    ios: 'com.liverso.order',
    android: 'com.liverso.order',
  }),
  boozeBrothers: Platform.select({
    ios: 'com.boozeBrother.order',
    android: 'com.boozeBrothers.order',
  }),
  magicalBookings: Platform.select({
    ios: 'com.magicalBookings.order',
    android: 'com.magicalBookings.order',
  }),
  ebay: Platform.select({
    ios: 'com.ebay.order',
    android: 'com.ebay.order',
  }),
  readyToRent: Platform.select({
    ios: 'com.readyToRent.order',
    android: 'com.readyToRent.order',
  }),
  theGenie: Platform.select({
    ios: 'com.theGenie.order',
    android: 'com.theGenie.order',
  }),
  sultanCenter: Platform.select({
    ios: 'com.sultanCenter.order',
    android: 'com.sultanCenter.order',
  }),
  reedas: Platform.select({
    ios: 'com.reedas.order',
    android: 'com.reedas.order',
  }),
  onebasket: Platform.select({
    ios: 'com.onerbasket.order',
    android: 'com.onerbasket.order',
  }),
  zozozi: Platform.select({
    ios: 'com.zozozi.order',
    android: 'com.zozozi.order',
  }),
  ekobridge: Platform.select({
    ios: 'com.ekobridge.order',
    android: 'com.ekobridge.order',
  }),
  ambosSafariExpress: Platform.select({
    ios: 'com.ambosSafariExpress.order',
    android: 'com.ambosSafariExpress.order',
  }),
  zulbrand: Platform.select({
    ios: 'com.zulbrand.order',
    android: 'com.zulbrand.order',
  }),
  emart: Platform.select({
    ios: 'com.emart.order',
    android: 'com.emart.order',
  }),
  spa: Platform.select({
    ios: 'com.customerApp.spa',
    android: 'com.customerApp.spa',
  }),
};

const socialKeys = {
  TWITTER_COMSUMER_KEY:
    getBundleId() == appIds.runrun
      ? 'OCOQeRWzRoDAnGNbNFsbN5kuk'
      : getBundleId() == appIds.royoorder
        ? 'R66DHARfuoYAPowApUxNxwbPi'
        : getBundleId() == appIds.capcorp
          ? 'R66DHARfuoYAPowApUxNxwbPi'
          : getBundleId() == appIds.tranzit
            ? 'iOOPhwfIqnQfmyjZqDbKzMNgP'
            : getBundleId() == appIds.hmoobhub
              ? 'AvNzKlREbm3Aan3sEKYbXv0k8'
              : 'R66DHARfuoYAPowApUxNxwbPi',
  TWITTER_CONSUMER_SECRET:
    getBundleId() == appIds.runrun
      ? 'zBfzttCBVAzimuaIsDWDU1MjqI4pWzvNsrW6YOYPVZtgtzTlN8'
      : getBundleId() == appIds.royoorder
        ? 'itcicJ7fUV3b73B8V05GEDBo4tzxGox2Si2q0BCk5pue327k15'
        : getBundleId() == appIds.capcorp
          ? 'itcicJ7fUV3b73B8V05GEDBo4tzxGox2Si2q0BCk5pue327k15'
          : getBundleId() == appIds.tranzit
            ? 'pg72uq6SVPkUn0Ts3lQWPfqHSXwR09Tb64d3bPrnIcPnZdd5Tq'
            : getBundleId() == appIds.hmoobhub
              ? '5UW5ukiVG49CmpAh7hBWP333K68gz8hfeUXzmoL3p6jIWy0qQa'
              : 'itcicJ7fUV3b73B8V05GEDBo4tzxGox2Si2q0BCk5pue327k15',
};

export { appIds, socialKeys, shortCodes };
