-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgkI1990GV4Y6QKqzJ
ZR0C/EhOQ6srMHFtz+k+GqI67gCgCgYIKoZIzj0DAQehRANCAASGLgSHdCVFwvI5
c9mUlLJC2aZrpTUeUbcyvscR1Z7RoXKbvBtFleSfT4qrBlwHQuAetFcq+wTkdbjO
XYsn6ajb
-----END PRIVATE KEY-----