-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg/1wLU+26B9xyIcDZ
JA1xal7kthMuWGq2Hbtk6xE8woegCgYIKoZIzj0DAQehRANCAAQVVMVc3wSk8ze/
yrWxdabBiI13TkcxXepHO5lo+ZdkSd/jmj6CuZTaCn67yjcvbtwos5wipiCrKAVe
X7UJd8WG
-----END PRIVATE KEY-----