-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgaCZ/3hqTE14TT2aO
mhapWwoLj+scPorwT3rhbKaWnOWgCgYIKoZIzj0DAQehRANCAAQNgMR6R9Rmrg6i
ULwTG5o5wyYaWgDu/JRL5BYo8x5FlggMex7PvJaB7RAhVzeIiPOpMUbvvFvlfCsL
7XeuOv7Q
-----END PRIVATE KEY-----