-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgzQRlJGn/ojsxZRkA
nuI56QtTD5kdfqAn0fdvfDHoaoWgCgYIKoZIzj0DAQehRANCAATCyvuEnLT62UCA
L1SAdVQ/SfR3vc02wrFt3sYji3R1oR5iiZCjqfAXxLGKMewYsvLMjcyqSx38SQuE
+1pdgHYl
-----END PRIVATE KEY-----