-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgJmwA+bMxb2FkquO0
pTG6QPk9HXky9rCfmFPCyd+q/u+gCgYIKoZIzj0DAQehRANCAAQDTeM+OrEhZ08k
JsxkSgYY2xTEQyyEHTqkXgzidvvFRmYP0Z20vp/FBW7dzICnZAfeEL6vqp6DWNFc
NvZsMBsy
-----END PRIVATE KEY-----