-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgCoxLbeV3ZdJ74lzy
W9yncMvpXUpwbymej3cPMrT8EgGgCgYIKoZIzj0DAQehRANCAARHkYfuK1g+2g2C
sYUMGiheEWLPM14sccY0Efpm/hsfVuG7B9fhWwv6j0B89a/rgrRrGrmPwLa3Kvkj
zrbGNbVg
-----END PRIVATE KEY-----