-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgB+61Ccnb6jpX6qwY
nQWqW8ORymjxviVdF5YqiwfUXpqgCgYIKoZIzj0DAQehRANCAATDhE3lUZOATKyT
wGVF4m59VCFngvkjYxNrN4LAfXbtW/ayMTNVAVf3UN8IckQbrq0n/KAIQFiTZhbd
2cM51IQC
-----END PRIVATE KEY-----