-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgkmbihgyU7Q5p4BL5
vfoxPAUV5slomoCCb8Fl7utkUtOgCgYIKoZIzj0DAQehRANCAAQK1IRUaKSC5LA/
i1I6Bqqix/fGU0xLdI+QwsQ5q4HFtfQkX3PMlO/+N7Ve9GnnHWQpLdDiEa7Hkuc2
S0MLaera
-----END PRIVATE KEY-----