-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgcscGolLvM6xVwhi8
9U+KZeOlhk2pHDUdI3440TxWSr6gCgYIKoZIzj0DAQehRANCAARuVHv5X+vZT5IZ
7Ti2upTENfVlTqzptkrWkuH+OIO/gveHOev87FwFUHwIdqOgJa3JltKfP2Pofj7b
VjoDk+yQ
-----END PRIVATE KEY-----