-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgIx4Dy69F1BkG9Tgh
BCzzq+QgV5ye35kI1BdRJVgnFWSgCgYIKoZIzj0DAQehRANCAAQylUfZKrYIQ3D2
im3zJnLYrfNyJSaWbSSLgi7gztz2Ukcei2FdNJrxoYRMwB14npRP0xVhJjok9W2k
xDEAN/nd
-----END PRIVATE KEY-----