-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQga9roOQC+itFJinRx
soCDuVTGrr9GL7PYsOkvOXVpsmSgCgYIKoZIzj0DAQehRANCAASmQBEO+LNY9F8+
2blwvc0iq05d0ICWadauD8qoW8Kn2sXizWfwhonsAxIXgCcp9jIwaseVfdgb5Inl
OG55R8rv
-----END PRIVATE KEY-----