-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgmzuoO1Kujha4uvEl
GIB3R6QrJSTg7T3INexormmoTfGgCgYIKoZIzj0DAQehRANCAAS4N+u7cQBlOGgW
/39rWIckZBhzQlMNfsdUbwyN/wXTaldCm9YoV/hNosrQq3r4rilCqA6kGf+ld/QV
eS6bO5Aw
-----END PRIVATE KEY-----