
# Resolve react_native_pods.rb with node to allow for hoisting
def node_require(script)
  # Resolve script with node to allow for hoisting
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve(
     '#{script}',
     {paths: [process.argv[1]]},
    )", __dir__]).strip
end

# === ENABLE NEW ARCHITECTURE & HERMES ===
ENV['RCT_NEW_ARCH_ENABLED'] = '1'
ENV['USE_HERMES'] = '1'

node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')
 
platform :ios, min_ios_version_supported
prepare_react_native_project!
 
 
linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

abstract_target 'available_pods' do
  rn_maps_path = '../node_modules/react-native-maps'
  use_frameworks! :linkage => :static
   config = use_native_modules!
   
   use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

   pod 'react-native-google-places', :path => '../node_modules/react-native-google-places'
   pod 'react-native-date-picker', :path => '../node_modules/react-native-date-picker'
  setup_permissions([
   'AppTrackingTransparency',
   'Bluetooth',
   'Calendars',
   'CalendarsWriteOnly',
   'Camera',
   'Contacts',
   'FaceID',
   'LocationAccuracy',
   'LocationAlways',
   'LocationWhenInUse',
   'MediaLibrary',
   'Microphone',
   'Motion',
   'Notifications',
   'PhotoLibrary',
   'PhotoLibraryAddOnly',
   'Reminders',
   'Siri',
   'SpeechRecognition',
   'StoreKit',
])
   
# 1 Ace Target
target 'Ace' do
 
end

# 2 GoKab Target
target 'GoKab' do
end

# 3 Grub Target
target 'Grub' do
 
end

# 4 Gusto Target
target 'Gusto' do
 
end

  # -------- Post Install Fixes --------
  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    # Ensure arm64 exclusion for simulator
    installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end

    # Disable code signing for bundle types
    installer.pods_project.targets.each do |target|
      if target.respond_to?(:product_type) && target.product_type == "com.apple.product-type.bundle"
        target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end

    # Remove problematic React-Core bundles
    installer.pods_project.targets.each do |target|
      if target.name == "React-Core.common-AccessibilityResources"
        target.remove_from_project
      end
    end
  end
end
